# Assignment 3

Question 1

In [2]:
import numpy as np
x=np.arange(2,51,3)
x


array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

Question 2

In [4]:
l1=[]
l2=[]

print("Enter element of 1st array: ")
for i in range(5):
    a=int(input())
    l1.append(a)

print("\nEnter element of 2nd array: ")
for i in range(5):
    b=int(input())
    l2.append(b)

arr1=np.array(l1)
arr2=np.array(l2)

conarr=np.concatenate((arr1, arr2))
print("\nConcatenated array:",conarr)

print("\nThe sorted arrays:")
A=np.sort(arr1)
B=np.sort(arr2)
C=np.sort(conarr)
print(A)
print(B)
print(C)

Enter element of 1st array: 
50
10
30
40
20

Enter element of 2nd array: 
35
15
25
45
55

Concatenated array: [50 10 30 40 20 35 15 25 45 55]

The sorted arrays:
[10 20 30 40 50]
[15 25 35 45 55]
[10 15 20 25 30 35 40 45 50 55]


Question 3

In [5]:
arr = []
a = int(input("Size of array:"))
for i in range(a):
    arr.append(int(input()))
arr1= np.array(arr)
print("\nArray:",arr1)
print("\nDimensions of array:", arr1.ndim)
print("\nSize of array:", arr1.size)

Size of array:5
1
2
3
4
5

Array: [1 2 3 4 5]

Dimensions of array: 1

Size of array: 5


Question 4

In [11]:
arr=np.arange(12)
print("1D array:",arr)
print("\nShape of 1D array:", arr.shape)

#newaxis function
print("\nUsing newaxis to convert 1D array to 2D array:")

row_change=arr[np.newaxis, :]
print("2D Array:",row_change)
print("\nShape of 2D array w.r.t rows:", row_change.shape)

col_change=arr[ :, np.newaxis]
print("\n2D Array:\n",col_change)
print("\nShape of 2D array w.r.t columns:", col_change.shape)

#expand_dims function
print("\nUsing expand-dim to convert 1D array to 2D array:")

r_change=np.expand_dims(arr, axis=0)
print("2D Array:",r_change)
print("\nShape of 2D array w.r.t rows:", r_change.shape)

c_change=np.expand_dims(arr, axis=1)
print("\n2D Array:\n",c_change)
print("\nShape of 2D array w.r.t columns:", c_change.shape)

1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Shape of 1D array: (12,)

Using newaxis to convert 1D array to 2D array:
2D Array: [[ 0  1  2  3  4  5  6  7  8  9 10 11]]

Shape of 2D array w.r.t rows: (1, 12)

2D Array:
 [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]

Shape of 2D array w.r.t columns: (12, 1)

Using expand-dim to convert 1D array to 2D array:
2D Array: [[ 0  1  2  3  4  5  6  7  8  9 10 11]]

Shape of 2D array w.r.t rows: (1, 12)

2D Array:
 [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]

Shape of 2D array w.r.t columns: (12, 1)


Question 5

In [12]:
#Consider two square arrays
sqarr1=np.array([[2,4,8],[3,6,9],[5,10,15]])
sqarr2=np.array([[7,14,21],[11,22,33],[13,26,39]])

#Vertical Stack
print("Vertical Append:\n",np.vstack((sqarr1,sqarr2)))

#Horizontal Stack
print("\nHorizontal Append:\n",np.hstack((sqarr1,sqarr2)))


Vertical Append:
 [[ 2  4  8]
 [ 3  6  9]
 [ 5 10 15]
 [ 7 14 21]
 [11 22 33]
 [13 26 39]]

Horizontal Append:
 [[ 2  4  8  7 14 21]
 [ 3  6  9 11 22 33]
 [ 5 10 15 13 26 39]]


Question 6

In [13]:
number_list = np.array([1, 1, 2, 3, 4, 4, 1,33,44,50,67,33,1,76,44,4,4,4,3])

(unique, counts) = np.unique(number_list, return_counts=True)
frequencies = np.asarray((unique, counts)).T
print("[Element Frequency]=")
print(frequencies)

[Element Frequency]=
[[ 1  4]
 [ 2  1]
 [ 3  2]
 [ 4  5]
 [33  2]
 [44  2]
 [50  1]
 [67  1]
 [76  1]]
